display_name = "Max" # Name of the character that would normally appear in-game
location = "center" # "left", "right", "center", etc
gender = "male" # "male" or "female" (used to determine text-click sounds)

# Arrays of strings for neutral, positive, and negative emotions
[sprites]
neutral = ["normal", "toss1", "toss2"]
positive = ["toss1", "toss2", "whatev"]
negative = ["billy", "sweating"]