display_name = "Lisa" # Name of the character that would normally appear in-game
location = "center" # "left", "right", "center", etc
gender = "female" # "male" or "female" (used to determine text-click sounds)

# Arrays of strings for neutral, positive, and negative emotions
[sprites]
neutral = ["normal"]
positive = ["smiling"]
negative = ["sweating"]